version: '3.8'

# Mongodb Service
services:
    db:
        image: mongo:latest # use the latest image.
        container_name: mongodb
        restart: unless-stopped
        environment: # set required env variables to access mongo
            MONGO_DB: ${MONGO_DB_NAME}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
 
        volumes: # optional to preserve database after container is deleted.
        - ./cavedata/dbdata:/data/db

    redis:
        container_name: redis
        image: "redis:alpine"
        restart: unless-stopped
        networks:
            - cave_net
        ports:
            - "6379:6379" 

    api:
        container_name: api
        build:
            context: .
            args:
                BUILD_SERVICE: api
            target: dev
        ports:
            - "9000:9000" 
        restart: unless-stopped
        depends_on: 
            - db
            - redis
        volumes:
            - ./cavedata/api:/cave/api
        environment:
            REDIS_PORT: 6379
            REDIS_HOST: redis 
        networks:
            - cave_net
    
    
    # frontend:
    #     build: ./web
    #     command: npm run start
    #     ports: 
    #         - "3000:3000"
    #     depends_on:
    #         - api
    #     volumes:
    #         - /web/node_modules
    #         - ./web:/web
    #     networks:
    #         - cave_net
    #     stdin_open: true

networks:
    cave_net: