

GET http://localhost:9000/auth

###Get a list of all products
GET http://65.21.16.90:9000/auth

### Create a product
put http://localhost:9000/auth
Content-Type: application/json

{
  "email": "onos9@adullam.ng",
  "password": "1234"
}

### GET a product by id
GET http://localhost:9000/user/5df118b3c86e5826958b661a
Content-Type: application/json
Authorization:

### Update a product by id
PUT  http://localhost:9000/user/5df118b3c86e5826958b661a
Content-Type: application/json

{
  "price": 5999
}


### Delete a product by id
DELETE  http://localhost:3000/products/5df118b3c86e5826958b661a

### 404 route Not Found
GET http://localhost:3000/abc_xyz
