version: '3.8'

# Mongodb Service
services:
    db:
        image: mongo:latest # use the latest image.
        container_name: mongo
        restart: unless-stopped
        networks:
            - net
        ports:
            - "27017:27017" 
        volumes: # optional to preserve database after container is deleted.
        - ../../cavedata/dbdata:/data/db

    redis:
        container_name: redis
        image: "redis:alpine"
        restart: unless-stopped
        networks:
            - net

    api:
        restart: unless-stopped
        command: -c chown -R ${UID}:${GID} /cave
        build:
            context: ../
            dockerfile: docker/Dockerfile
            target: dev
        ports:
            - "2345:2345"
            - "9000:9000" 
        networks:
            - net
        env_file: # set required env variables 
            - ./.env
        depends_on: 
            - db
            - redis
        volumes:
            - ../../cavedata/api:/cave/api
            - ../../cavedata/go-modules:/go/pkg/mod
        
    # frontend:
    #     restart: unless-stopped
    #     build:
    #         context: ../
    #         dockerfile: docker/Dockerfile
    #         target: dev
    #     ports: 
    #         - "3000:3000"
    #     depends_on:
    #         - api
    #     volumes:
    #         - /web/node_modules
    #         - ./web:/web
    #     networks:
    #         - net
    #     stdin_open: true

networks:
    net: