version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        networks:
            - net
        ports:
            - "27017:27017" 
        volumes:
        - ../../cavedata/dbdata:/data/db

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

    redis:
        image: "redis:alpine"
        container_name: redis
        restart: unless-stopped
        networks:
            - net
        
    nginx:
        image: nginx:latest
        container_name: nginx
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - net
        volumes:
            - ../../cavedata/web:/var/www/html/
            - ../../cavedata/logs/nginx:/var/log/nginx/
      
    php:
        image: php:fpm-alpine
        container_name: php
        networks:
            - net
        volumes:
            - ../../cavedata/web:/var/www/html

    api:
        image: api:1.0.2
        restart: unless-stopped
        build:
            context: ../
            dockerfile: docker/Dockerfile
            target: api
        ports:
            - "2345:2345"
            - "8000:8000" 
        env_file:
            - ../.env
        depends_on: 
            - mongodb
            - redis
            - nginx
            - php
        volumes:
            - ../../cavedata/api:/cave/api
            - ../../cavedata/go-modules:/go/pkg/mod
        networks:
            - net
networks:
    net: