version: '3.8'

# Mongodb Service
services:
    db:
        image: mongo:latest # use the latest image.
        container_name: mongo
        restart: unless-stopped
        networks:
            - cave_net
        ports:
            - "27017:27017" 
        volumes: # optional to preserve database after container is deleted.
        - ../../cavedata/dbdata:/data/db

    redis:
        container_name: redis
        image: "redis:alpine"
        restart: unless-stopped
        networks:
            - cave_net

    api:
        container_name: api
        build:
            context: ../
            dockerfile: docker/Dockerfile
            target: prod
        ports:
            - "2345:2345"
            - "9000:9000" 
        networks:
            - cave_net
        restart: unless-stopped
        environment: # set required env variables to access mongo
            MONGO_URI: ${MONGO_URI}
        depends_on: 
            - db
            - redis
        volumes:
            - ../../cavedata/api:/cave/api
        command: -c chown -R ${UID}:${GID} /cave
    
    
    # frontend:
    #     build: ./web
    #     command: npm run start
    #     ports: 
    #         - "3000:3000"
    #     depends_on:
    #         - api
    #     volumes:
    #         - /web/node_modules
    #         - ./web:/web
    #     networks:
    #         - cave_net
    #     stdin_open: true

networks:
    cave_net: